# Generated by Django 2.0.1 on 2018-03-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jibambeuser',
            name='user',
        ),
    ]
