# Generated by Django 2.0.1 on 2018-03-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180306_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jibambeuser',
            name='expire',
            field=models.DateTimeField(default='0, 0, 0, 0'),
        ),
    ]
