# Generated by Django 2.0.1 on 2018-03-06 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180306_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jibambeuser',
            name='expire',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 2, 4, 57, 222258)),
        ),
    ]
