# Generated by Django 2.0.1 on 2018-03-06 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180306_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jibambeuser',
            name='expire',
        ),
        migrations.AddField(
            model_name='jibambeuser',
            name='subscription_expire',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 2, 12, 3, 632061)),
        ),
    ]
