# Generated by Django 2.0.1 on 2018-03-06 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180306_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='jibambeuser',
            name='subscription_expired',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='jibambeuser',
            name='subscription_expire',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 2, 14, 9, 146308)),
        ),
    ]
