# Generated by Django 2.0.1 on 2018-03-06 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20180306_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jibambeuser',
            name='subscription_expire',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 7, 2, 49, 17, 183600)),
        ),
    ]
