# Generated by Django 2.0.1 on 2018-03-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20180306_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jibambeuser',
            name='subscription_expire',
            field=models.DateTimeField(default=[2018, 3, 6, 6, 2, 53, 59037]),
        ),
    ]
