# Generated by Django 2.0.1 on 2018-03-06 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180306_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jibambeuser',
            name='subscription_expire',
            field=models.DateTimeField(default=datetime.datetime(1994, 3, 6, 6, 2, 53, 59037)),
        ),
    ]
