# Generated by Django 2.0.1 on 2018-03-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20180306_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='jibambeuser',
            name='device_mac',
            field=models.CharField(default='00:00:00:00', max_length=100, unique=False),
        ),
    ]
