# Generated by Django 2.0.1 on 2018-03-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_jibambeuser_device_mac'),
    ]

    operations = [
        migrations.CreateModel(
            name='JibambePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_phone', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=10)),
                ('transaction_reference', models.CharField(max_length=10)),
            ],
        ),
    ]
