# Generated by Django 2.0.1 on 2018-03-07 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_jibambepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jibambepayment',
            name='transaction_timestamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
