# Generated by Django 2.0.1 on 2018-03-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_jibambepayment_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jibambepayment',
            name='transaction_timestamp',
            field=models.CharField(max_length=100),
        ),
    ]
