# Generated by Django 2.0.1 on 2018-01-20 04:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('thumbnail', models.CharField(max_length=120)),
                ('source_url', models.CharField(max_length=500)),
                ('duration', models.TimeField(default=datetime.timedelta(0, 7200))),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('added_on',),
            },
        ),
        migrations.CreateModel(
            name='MoviesCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movies', to='movies.MoviesCategories'),
        ),
    ]
